channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - arviz
  - bambi
  - biopython
  - dask-jobqueue
  - dask[version='<2024.8.1']
  - datashader
  - ensembl-vep=112.0
  - fancyimpute
  - fastparquet
  - firefox
  - gcta
  - geckodriver
  - h5py
  - hdbscan
  - holoviews
  - hvplot
  - ipykernel
  - ipywidgets
  - jinja2=3.1.2
  - lightgbm
  - mygene
  - nbformat
  - ncbi-datasets-cli
  - nltk
  - openjdk=11
  - pandas
  - panel
  - pip
  - plink
  - plotly
  - prophet
  - psycopg2
  - pyarrow
  - pygraphviz
  - pymc[version='>=5']
  - pytables
  - python=3.11
  - scikit-image
  - scikit-learn
  - scikit-optimize
  - seaborn
  - selenium
  - shap
  - snpeff
  - sqlalchemy
  - tabulate
  - umap-learn
  - xgboost
  - ydata-profiling