{% set name = "gwas" %}
{% set version = "0.4.0" %}

package:
  name: {{name}}
  version: {{version}}

source:
  url: https://github.com/sanchestm/GWAS-pipeline/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8050bb0187c4d7ef4b947a00fd67f13ea6d80dd5eb3a0ac445bf8ed5ec52a79b

build:
  noarch: python
  number: 0
  script: build.sh

requirements:
  build:
    - python
    - pip
  run:
    - python >=3.10,<3.13
    - pandas
    - fastparquet
    - seaborn
    - umap-learn
    - ipywidgets
    - dask
    - psycopg2
    - scikit-learn
    - openjdk=11
    - ipykernel
    - jax
    - pyarrow
    - plink
    - plink2
    - snpeff
    - dask-jobqueue
    - gcta
    - plotly
    - biopython
    - mygene
    - pytables
    - h5py
    - hdbscan
    - ydata-profiling
    - arviz
    - prophet
    - lightgbm
    - shap
    - scikit-optimize
    - xgboost
    - nltk
    - pygraphviz
    - sqlalchemy
    - ncbi-datasets-cli
    - panel
    - hvplot
    - holoviews
    - fancyimpute
    - scikit-image
    - selenium
    - datashader
    - nbformat
    - firefox
    - jinja2 #=3.1.2
    - geckodriver
    - tabulate
    - ensembl-vep=112.0
    - pymc[version='>=5']
    - bambi
    - pysam
    - pdf2image
    - r-base
    - r-essentials
    - r-chron
    - r-vctrs
    - r-kableextra
    - r-rjsonio
    - r-dt
    - r-htmltools
    - r-httr
    - r-openxlsx
    - r-rmarkdown
    - r-plyr
    - r-readxl
    - pandoc
    - r-purrr
    - r-dplyr
    - r-data.table
    - imagemagick
    - transformers
    - python-kaleido
    - accelerate
    - pip
  pip:
    - goatools
    - dash-bio==1.0.1

test:
  imports:
    - gwas.gwas 
    - gwas

about:
  home: https://github.com/sanchestm/GWAS-pipeline
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A general package to run GWAS associations and visualize the results"

extra:
  recipe-maintainers:
    - sanchestm

