{% set name = "gwas_pipeline" %}
{% set version = "0.3.7" %}

package:
  name: {{name}}
  version: {{version}}

source:
  path: .

build:
  number: 0
  script: python -m pip install .

requirements:
  build:
    - python
    - pip
  run:
    - python=3.11
    - pandas
    - fastparquet
    - seaborn
    - umap-learn
    - ipywidgets
    - dask<2024.8.1
    - psycopg2
    - scikit-learn
    - openjdk=11
    - ipykernel
    - pyarrow
    - plink
    - snpeff
    - dask-jobqueue
    - gcta
    - plotly
    - biopython
    - mygene
    - pytables
    - h5py
    - hdbscan
    - ydata-profiling
    - arviz
    - prophet
    - lightgbm
    - shap
    - scikit-optimize
    - xgboost
    - nltk
    - pygraphviz
    - sqlalchemy
    - ncbi-datasets-cli
    - panel
    - hvplot
    - holoviews
    - fancyimpute
    - scikit-image
    - selenium
    - datashader
    - nbformat
    - firefox
    - jinja2=3.1.2
    - geckodriver
    - tabulate
    - ensembl-vep=112.0
    - pymc>=5
    - bambi
    - pdf2image
    - r-base
    - r-essentials
    - r-chron
    - r-vctrs
    - r-kableextra
    - r-rjsonio
    - r-dt
    - r-htmltools
    - r-httr
    - r-openxlsx
    - r-rmarkdown
    - r-plyr
    - r-readxl
    - pandoc
    - r-purrr
    - r-dplyr
    - r-data.table
    - imagemagick
    - pip
    - pip:
      - pandas-plink>=2.3
      - goatools
      - dash-bio==1.0.1
      - kaleido
      - transformers
      - accelerate
      - enformer-pytorch


test:
  imports:
    - gwas_pipeline.gwas_class_auto  # Ensure the module can be imported
    - gwas_pipeline

about:
  home: https://github.com/sanchestm/GWAS-pipeline
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A general package to run GWAS associations and visualize the results"

extra:
  recipe-maintainers:
    - sanchestm

channels:
  - conda-forge
  - defaults
  - bioconda
