name: gpu
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.12
  - cudf=25.04
  - cuml=25.04
  - cugraph=25.04
  - cuvs=25.04
  - cupy
  - jax
  - dask
  - dask-cuda=25.04
  - dask-jobqueue
  - kvikio
  - cuda-cudart
  - cuda-toolkit
  - pandas
  - fastparquet
  - seaborn
  - umap-learn
  - ipywidgets
  - psycopg2
  - scikit-learn
  - openjdk=11
  - ipykernel
  - pyarrow
  - plink
  - gcta
  - plotly
  - biopython
  - mygene
  - pytables
  - h5py
  - pysam
  - ocl-icd-system
  - clinfo
  - hdbscan
  - ydata-profiling
  - arviz
  - prophet
  - lightgbm
  - shap
  - scikit-optimize
  - xgboost
  - nltk
  - pygraphviz
  - sqlalchemy
  - ncbi-datasets-cli
  - panel
  - hvplot
  - holoviews
  - fancyimpute
  - scikit-image
  - selenium
  - datashader
  - nbformat
  - firefox
  - jinja2 #=3.1.2
  - geckodriver
  - tabulate
  - ensembl-vep=112.0
  - pymc[version='>=5']
  - bambi
  - transformers
  - python-kaleido
  - accelerate
  - pdf2image
  - boost
  - r-base
  - r-essentials
  - r-chron
  - r-vctrs
  - r-kableextra
  - r-rjsonio
  - r-dt
  - r-htmltools
  - r-httr
  - r-openxlsx
  - r-rmarkdown
  - r-plyr
  - r-readxl
  - pandoc
  - pytorch=*=*cuda*   
  - r-purrr
  - r-dplyr
  - r-data.table
  - imagemagick
  - pip
  - pip:
    - goatools
    - dash-bio==1.0.1
    #- enformer-pytorch    # uncomment this line when you’re ready to reinstall


